### PR TITLE
feat: add ipfs.mihir.ch

### PR DESCRIPTION
**Pull request by plibither8**
* Gateway URL: https://ipfs.mihir.ch/ipfs/:hash
* Geographic location: India

### CODE REVIEW

**Review by jessicaschilling — CHANGES_REQUESTED** [review]
Folks using this gateway will get a certificate name mismatch error:
image
Can you please remedy this before it's merged?

**Comment by plibither8** [comment]
Thanks for bringing this to notice, I'll fix this ASAP.

**Comment by plibither8** [comment]
@jessicaschilling could you please check it out once again? I think I've fixed the issue from my end :)

**Comment by jessicaschilling** [comment]
LGTM! Thanks for fixing the cert 😊

**Comment by plibither8** [comment]
Awesome :smile:

**Pull request merged**
