### PR TITLE
Stray path character

### PR DESCRIPTION
**Pull request by jessicaschilling**

### CODE REVIEW

**Comment by xmaysonnave** [comment]
Thanks for your quick action.
It seems that I've a wrong cors setup though. That one is on my side... 
Warmly

**Comment by xmaysonnave** [comment]
While clicking on bluelight.link I'm redirecting to my server. The expected result should be the hello page. However the url is not properly built. /ipfs/ is missing:

https://bluelight.link/bafybeifx7yeb55armcsxwwitkymga5xf53dxiarykms3ygqic223w5sk3m#x-ipfs-companion-no-redirect

Is there anything to do on my side?

Thanks

**Comment by jessicaschilling** [comment]
Ah, got it. https://github.com/ipfs/public-gateway-checker/pull/132 takes care of that.

**Comment by xmaysonnave** [comment]
I confirm. It's fixed.
Thanks

**Pull request merged**
