### PR TITLE
feat: add the Alterdot Network IPFS gateway

### PR DESCRIPTION
**Pull request by andrewtookay**
The Alterdot project is about merging together the two powerful technologies of blockchain and IPFS, therefore we maintain a public IPFS gateway ourselves.

- SSL
- Origin Isolation / Subdomain Resolution

### CODE REVIEW

**Review by lidel — CHANGES_REQUESTED** [review]
@andrewtookay  https://gateway.alterdot.network/ipfs/QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR returns Error 404

**Comment by andrewtookay** [comment]
it's fixed now

**Comment by andrewtookay** [comment]
@lidel any updates? it's been almost 2 weeks now

**Review by lidel — CHANGES_REQUESTED** [review]
@andrewtookay it now timeouts (both `/ipfs` and  https://gateway.alterdot.network/ipns/en.wikipedia-on-ipfs.org) 

I don't think it is  something on my end (I'm in Europe), got same results when testing from other locations, but lmk

**Comment by andrewtookay** [comment]
The gateway was working correctly at times but we encountered some issues along the way, including DDoS attacks and connectivity problems of the IPFS daemon. Unfortunately, these issues manifested when the gateway was tested, but we will do another setup of the gateway and get rid of existing problems. I'll let you know when it's up and running, hopefully this time we can get added to the list.

**Comment by lidel** [comment]
Ack,Thanks!
I'm closing this for now, please open a new PR when your situation stabilizes.

**Pull request closed without merging**
