### PR TITLE
Preventing CORB + some explanatory comments

### PR DESCRIPTION
**Pull request by lazyweirdo**
This mother f*cker PR is never going to be merged ... go ahead, lets add a gateway with CORS disabled and CORB enabled so we see it DOWN no matter what :kissing:

### CODE REVIEW

**Comment by jamiew** [comment]
Working great, thank you kindly. And for your patience :)

**Comment by jamiew** [comment]
Interestingly still see these two content-type errors -- but much less than before. Is this a gateway misconfiguration issue?

2019-12-18 at 15-58-20 Public IPFS Gateways

**Comment by lazyweirdo** [comment]
> Interestingly still see these two content-type errors -- but much less than before. Is this a gateway misconfiguration issue?

Oh ... yes ...  it seems those gateways are not correctly guessing a mime type ... maybe there is something else i can do

> Working great, thank you kindly. And for your patience :)

i really love you all :kissing:

**Comment by lidel** [comment]
> Interestingly still see these two content-type errors -- but much less than before. Is this a gateway misconfiguration issue?
> 
> 2019-12-18 at 15-58-20 Public IPFS Gateways

Yes, looks like Nginx with custom rules. Expected to fail in that scenario.

**Pull request merged**
