### PR TITLE
feat: add ipfs.1-2.dev

### PR DESCRIPTION
**Pull request by SoftCreatR**
n/t

### CODE REVIEW

**Review by lidel — CHANGES_REQUESTED** [review]
@SoftCreatR it does not seem to wotk with IPNS (https://ipfs.1-2.dev/ipns/en.wikipedia-on-ipfs.org) – mind fixing?

**Comment by SoftCreatR** [comment]
I'll check that :)

**Comment by SoftCreatR** [comment]
Done. Took me some time, to figure out how to properly make it work in a subdomain environment.

**Review by lidel — APPROVED** [review]
Thanks! 

What do you mean by:
> Would be nice if go-ipfs would handle the character replacements by it's own. 
?

**Comment by SoftCreatR** [comment]
> Thanks!
> 
> What do you mean by:
> 
> > Would be nice if go-ipfs would handle the character replacements by it's own.
> > ?

Replacing `.` by `-` and `-` by `--` is somewhat, the Webserver shouldn't do by it's own, when using a subdomain setup. Since ipfs performs the redirect, it should also handle these rewrites.

**Comment by lidel** [comment]
Mind providing examples? Afaik go-ipfs does all redirects it can (without breaking TLS, as wildcart certs work only for a single label wildcard).

**Comment by SoftCreatR** [comment]
The one mentioned: https://ipfs.1-2.dev/ipns/en.wikipedia-on-ipfs.org

go-ipfs is configured for Subdomains, so what it does (or did during my tests) was to redirect to en.wikipedia-on-ipfs.org.ipfs.ipfs.1-2.dev, which isn't working due to the lack of wildcard cert depth.

**Comment by SoftCreatR** [comment]
> It sounds you are doing redirects from https://ipfs.1-2.dev/* to https://*.ipfs.1-2.dev/ subdomains at the level of some reverse proxy (nginx?), which is not smart enough to do necessary DNS label normalization.

No, these redirects are handled by IPFS via `proxy_pass http://gateway;`, which works just fine, using this IPFS config:

```json
"PublicGateways": {
  "*.1-2.dev": {
    "NoDNSLink": false,
    "Paths": [
      "/ipfs",
      "/ipns"
    ],
    "UseSubdomains": true
  }
},
```

After your request regarding IPNS, I've implemented this:

```lua
    location ~ ^/ipns/(?<name>.*) {
        rewrite_by_lua_block
        {
            local subdomain = ngx.var.name
            subdomain = string.gsub(subdomain, "%-", "--")
            subdomain = string.gsub(subdomain, "%.", "-")
            
            return ngx.redirect(ngx.var.scheme .. "://" .. subdomain .. ".ipns." .. ngx.var.host, 301)
        }
    }
```

which isn't by far not the most beautiful and convenient solution, but it works so far.

What I didn't know was, that `proxy_set_header X-Forwarded-Proto https` simply does the trick. So I've removed the lua part and simply added that line and it works, as expected :)

**Pull request merged**
