### PR TITLE
Nicer look

### PR DESCRIPTION
**Pull request by lazyweirdo**
Just changed its look a little bit based on @fsdiogo 's work ... related to #79 

test it: https://lazyweirdo.github.io/public-gateway-checker/

In reference to ipfs/ipfs-gui#80 ... preparing things for

@olizilla
> Allow folks to submit new gateways via a PR in Github, including gateway url, Contact email, Developer or Company name and logo - to celebrate those offering public infrastructure)
> Clearly Link to it or incorporate the information into the main https://ipfs.io wesite along with links to information about how to run your own
> Create a map visualization of where are all the IPFS Gateways in the World.

@alanshaw 
> Things I'd also like to know status of:
> - Preload nodes
> - Public WebRTC and Websocket star rendezvous servers

Last one i don't know if it is still needed because of libp2p/js-libp2p#385 however, i feel *-star are going to be there longer than we would like, just as our beloved gateways

:kissing_heart: :kissing_heart:

WIP ... feel free to modify it

### CODE REVIEW

**Comment by jamiew** [comment]
I dig it, only change I'd propose might be a max-width on desktop so that the "response" field isn't pushed so far to the right. Looks great on mobile but awkward on 600px+

I'm not at a desktop till later but can add that later

**Comment by lazyweirdo** [comment]
> I dig it, only change I'd propose might be a max-width on desktop so that the "response" field isn't pushed so far to the right. Looks great on mobile but awkward on 600px+
> 
> I'm not at a desktop till later but can add that

sure ... max-width: 1024px; maybe ? ... im also going to change the way they get sorted ...

**Comment by lazyweirdo** [comment]
Done ... WIP ... feel free to modify it

**Comment by jamiew** [comment]
Looks great, ty!

**Pull request merged**
