### PR TITLE
feat: add starbase.gw3.io

### PR DESCRIPTION
**Pull request by jzhu-eth**
Starbase is a decentralized IPFS gateway service, operating as a collective of IPFS kubo nodes from around the world. We are committed to the principles of decentralization, allowing third-party nodes to join and contribute to our gateway. Our aim is to provide a user-friendly interface for seamless interaction with the IPFS network.

This gateway is part of our commitment to our IPFS open grants:  https://github.com/ipfs/devgrants/blob/master/open-grants/open-proposal-distributed-pinning-protocol.md
Website: https://www.gw3.io/

### CODE REVIEW

**Comment by SgtPooki** [comment]
FYI @jzhu-eth it looks like the gateway is failing the gateway tests at the preview url: https://bafybeif6sqkoj6hadml7rflta3icmykmjhm24bac3qf47ama7rcte25m3q.on.fleek.co/

image

**Review by SgtPooki — CHANGES_REQUESTED** [review]
Ideally, we would like at least some of the gateway checks to be passing. Please let us know if we can help at all

**Comment by jzhu-eth** [comment]
[SgtPooki](https://github.com/SgtPooki)
We have resolved the previous issue concerning cross-origin HTTPS requests in certain browsers. Our gateway should now pass the public checker's testing procedures. Could you please perform the tests on our gateway once again?

We appreciate your time and consideration.

**Comment by SgtPooki** [comment]
@jzhu-eth looks much better:

image

**Pull request merged**
