### PR TITLE
feat: add Onion Gateway (TOR) [subdomain gateway] - http://fzdqwfb5ml56oadins5jpuhe6ki6bk33umri35p5kt2tue4fpws5efid.onion

### PR DESCRIPTION
**Pull request by StorryTV**
http://fzdqwfb5ml56oadins5jpuhe6ki6bk33umri35p5kt2tue4fpws5efid.onion

No SSL
With Subdomain Gateway
Only accessible using TOR

### CODE REVIEW

**Comment by StorryTV** [comment]
This one works (Also with subdomain IPFS gateway): http://fzdqwfb5ml56oadins5jpuhe6ki6bk33umri35p5kt2tue4fpws5efid.tor2web.to/ipfs/bafybeifx7yeb55armcsxwwitkymga5xf53dxiarykms3ygqic223w5sk3m

So, ".onion" is replaced by ".tor2web.to"

The only problems are:

- It always returns statuscode 200 even if it's not available, so it has to be strictly checked by the response.
- It has to be requested with http and not with https

I don't know of a way to check the status through a library or just js for now (without starting TOR [which is too much just for checking a few gateways])

**Comment by StorryTV** [comment]
Checking the status through such a TOR2Web gateway on clearnet is fine for just checking it's availability, but is not recommended for browsing.

**Comment by lidel** [comment]
I'd say we wait for #194  to land, then we can add special-casing for gateways under `*.onion`:
- check  to check their availability via `.onion` natively
  - if that fails, re-try via TOR2Web but show original `.onion` on the list  / links
  
This way the status will be displayed correctly in both regular browser and Tor Browsers

**Comment by StorryTV** [comment]
Sure, I'll wait for that :)

That seems like a good way to approach it, so that it also shows up in regular browsers besides only TOR.

**Review by lidel — CHANGES_REQUESTED** [review]
@StorryTV mentioned PR got merged, you should be able to rebase and add  `.onion` support/preview (if you still have bandwidth)

**Comment by StorryTV** [comment]
I pushed a new commit #212 so this one can be closed if you want

**Pull request closed without merging**
