### PR TITLE
(fix): Follow Up to 310 - Adding more details to failed trustless test

### PR DESCRIPTION
**Pull request by whizzzkid**
Follow up to #310.

In this PR:
- Adding failed to tests to the debug messages.

### CODE REVIEW

**Review by lidel — COMMENTED** [review]
nit: mind renaming "Trustless" to “Block/CAR”  and link to end user docs at  https://docs.ipfs.tech/reference/http/gateway/#trustless-verifiable-retrieval  instead of gateway specs? :pray:

**Comment by whizzzkid** [comment]
@lidel fixed

block:car

This may move the spacing in #313

**Comment by SgtPooki** [comment]
> [#trustless-verifiable-retrieval](https://docs.ipfs.tech/reference/http/gateway/#trustless-verifiable-retrieval)

I prefer "trustless" as that's how we're advertising it to customers, but block/car is direct and a link to the docs should help anyone understand if they want to know more

**Review by SgtPooki — APPROVED** [review]

**Comment by lidel** [comment]
s/customers/users/ :)) 

yeah, this should be good enough until we clean up naming across docs and specs.


Digression:

I've heard some constructive feedback that "Trustless" is  too vague, and confusing:
while you can verify blocks, you still "Trust" gateway with your privacy (gateway can track what CIDs you requested).

"Block/CAR" is very clear, but too technical. I wonder if "verifiable" is a better term overall?
I'd like us to unify this across docs and specs at some point, but naming is not my strong suit.  :)

**Pull request merged**
