### PR TITLE
Add ipfs.cosmos-ink.net

### PR DESCRIPTION
**Pull request by LinusCDE**
Hi,
this is my own (now public) instance.

I use this server for a number of (non stressing) things.  
I plan to keep the IPFS server running which is in a docker behind an nginx server.

### CODE REVIEW

**Comment by jessicaschilling** [comment]
Hi @LinusCDE -- apologies for the lengthy review, and thanks to @lazyweirdo for calling out attention on this one.

**Comment by LinusCDE** [comment]
Not a problem at all. It wasn't urgent anyway.
I also can understand such long durations. Once a project is more or less done and I moved on to another it also takes me a while to react to older projects (or they drown in my inbox for several weeks).

**Comment by LinusCDE** [comment]
I also just added support for Origin/Subdomain ([commit here](https://github.com/LinusCDE/public-gateway-checker/commit/cd5deef39c2fb7aef05784836fa2463c1f143b2f)).

Would be nice if you could merge that. I can also create a new pull request if necessary.

**Comment by jessicaschilling** [comment]
Do you mind a new PR? Thanks!

**Comment by jessicaschilling** [comment]
Hey @LinusCDE -- don't worry about the separate PR, just updated it (was AFK for a few days due to an emergency but have my tools back now!) ... see https://github.com/ipfs/public-gateway-checker/pull/97

**Comment by LinusCDE** [comment]
Top. Thanks for merging. The server will also get a decent upgrade soon and be a lot faster.
A shared hdd is the worst (comparable to MicroSD performance).

**Pull request merged**
