### PR TITLE
[Cleanup] dead gateway , domain expired

### PR DESCRIPTION
**Pull request by gkimgi**

### CODE REVIEW

**Comment by SgtPooki** [comment]
I just merged https://github.com/ipfs/public-gateway-checker/pull/276. Can you rebase and update with a clarification about what criteria you're using to remove these?

**Comment by gkimgi** [comment]
These removed gateways have been failing for a long time.

I'm watching and check those services one by one.

These services fail for reasons that are no longer available and are not temporary service failures.
such as ...
gateway failed,Error 522,502 Bad Gateway,offline,domain expired , ipns failed

Some items seem to fail temporarily. So I ignored it.

**Comment by waybackarchiver** [comment]
CDN captcha checks are used by some domains.

**Comment by gkimgi** [comment]
@waybackarchiver
I check those services one by one.
some domains captcha check ,  I ignore them.

**Comment by inipfs** [comment]
@gkimgi Thanks for your works!

It seems that `ipfs.yt`, `dweb.eu.org` and `permaweb.eu.org` works again, but slowly. Please ignore them.

**Comment by hacdias** [comment]
> @gkimgi Thanks for your works!
> 
> It seems that `ipfs.yt`, `dweb.eu.org` and `permaweb.eu.org` works again, but slowly. Please ignore them.

I think this is one of the dangers with this PR. What if some gateways start working again? 

Instead of this PR, we should focus on a method do periodically check the gateways (see #281), such that we have a specific amount of time that we give a gateway to come back up again (e.g. 1 month). After that, it is automatically removed. We need clear guidelines for that.

**Pull request closed without merging**
