### PR TITLE
fix(gateways): Removing Offending Gateways

### PR DESCRIPTION
**Pull request by whizzzkid**
Closes: #433 

CC: @SgtPooki @BigLep 

This doesn't feel sustainable, maybe the need is to evangelize https://badbits.dwebops.pub/ more.

### CODE REVIEW

**Comment by twdragon** [comment]
@whizzzkid I blocked programmatically case-sensitive CIDs on the gateway, and passed the exclusion request to Google. Hope now the gateway will be considered safe, cause it will support only subdomains

**Comment by SgtPooki** [comment]
@whizzzkid it would be nice if we could check a gateway's support of the badbits list

**Comment by SgtPooki** [comment]
@aschmahmann @lidel do you have any recommendations here?

**Comment by BigLep** [comment]
Agreed that more badbits usage is a good thing (but obviously each user should choose what is right for them).  In 2023 Kuibo will get a primitive in place making it more self-service to consume and use such lists: https://github.com/ipfs/kubo/issues/8492

In terms of determining whether a gateway supports badbits, I think the easiest way to do that is to grab some random CIDs from the list and check what happens when you request them from the gateway.

That said, this browser red screen of death will go away when gateway stats (besides ping) are handled in CI (rather than from each browser).  There were plans discussed this week of moving in that direction: https://pl-strflt.notion.site/Gateway-Conformance-Dashboards-10490048436e456d99d40016586a6937#cf9d867edd2043619894e5eab4c36bfc

**Comment by twdragon** [comment]
@whizzzkid @SgtPooki @BigLep the gateway domain passed the Google checkup, so we can use it, but it is now supporting only the subdomain addressing schema

**Comment by twdragon** [comment]
@whizzzkid yes, I will do. Please note that the gateway do not support anymore CID v0 and requires only subdomain-based requests. Is it a problem?

**Review by SgtPooki — APPROVED** [review]

**Comment by SgtPooki** [comment]
> Please note that the gateway do not support anymore CID v0 and requires only subdomain-based requests. Is it a problem?

That should be fine, subdomain-based requests are more secure

**Pull request merged**
