### PR TITLE
feat: add public.records gateway

### PR DESCRIPTION
**Pull request by theshakeweb**
Public.records is a gateway on Handshake, secured by DANE. To access the public.records gateway, a Handshake resolver is required, such as https://impervious.com/fingertip or https://impervious.com/beacon.

### CODE REVIEW

**Comment by SgtPooki** [comment]
## With fingertip running (auto config)
image

## Without fingertip running
image

@lidel @meandavejustice How do you feel about adding this gateway? I imagine it could make the CI workflows more difficult

**Comment by SgtPooki** [comment]
This also brings up an interesting question.. should we provide a way for gateways to supply prereq info? For this gateway, users need a [Handshake](https://handshake.org/) resolver. Displaying that information could be useful

**Comment by SgtPooki** [comment]
@theshakeweb would you be willing to create a github action that supports validation of Handshake URLs? It looks like the test at https://github.com/handshake-org/hsd/blob/master/test/http-test.js does mostly what we would need. Without that, adding this gateway would block any PRs once #248 is done.

**Comment by theshakeweb** [comment]
> @theshakeweb would you be willing to create a github action that supports validation of Handshake URLs? It looks like the test at https://github.com/handshake-org/hsd/blob/master/test/http-test.js does mostly what we would need. Without that, adding this gateway would block any PRs once #248 is done.

Understood. Yes, willing to create this github action. Thanks for your thoughtful consideration.

**Comment by SgtPooki** [comment]
> > @theshakeweb would you be willing to create a github action that supports validation of Handshake URLs? It looks like the test at https://github.com/handshake-org/hsd/blob/master/test/http-test.js does mostly what we would need. Without that, adding this gateway would block any PRs once #248 is done.
> 
> Understood. Yes, willing to create this github action. Thanks for your thoughtful consideration.

That's fantastic! We would greatly appreciate it =)

**Comment by lidel** [comment]
> How do you feel about adding this gateway? I imagine it could make the CI workflows more difficult

FWIW we already have `.onion`, so with HNS we have two use cases of special gateways that require custom routing or resolver.

That is fine – people who have that will see them as online.

Would be nice to have ability to  test them on CI, so they are not mistaken for invalid ones and removed during periodical cleanup (like we did in #40)

**Comment by SgtPooki** [comment]
Opened https://github.com/ipfs/public-gateway-checker/issues/364 for addressing special request handling URLs in CI

However, @theshakeweb, it looks like public.records/ipfs gateway is no longer working. I tried at the [preview](https://bafybeifpvlg43a4kkxmspnnzrdos5tzmefoq4nux3f2uc424f2cqtaftji.on.fleek.co/) as well as locally, and neither are working using fingertip+brave nor with the beacon browser

URL to test: https://public.records/ipfs/bafybeibwzifw52ttrkqlikfzext5akxu7lz4xiwjgwzmqcpdzmp3n5vnbe?now=1673382715453&filename=1x1.png#x-ipfs-companion-no-redirect

**Comment by theshakeweb** [comment]
> Opened #364 for addressing special request handling URLs in CI
> 
> However, @theshakeweb, it looks like public.records/ipfs gateway is no longer working. I tried at the [preview](https://bafybeifpvlg43a4kkxmspnnzrdos5tzmefoq4nux3f2uc424f2cqtaftji.on.fleek.co/) as well as locally, and neither are working using fingertip+brave nor with the beacon browser
> 
> URL to test: https://public.records/ipfs/bafybeibwzifw52ttrkqlikfzext5akxu7lz4xiwjgwzmqcpdzmp3n5vnbe?now=1673382715453&filename=1x1.png#x-ipfs-companion-no-redirect
> 
> image

You are correct. The gateway is still active but had to be relocated to a new Handshake domain. It now operates at shake.speare/ipfs.

**Review by SgtPooki — CHANGES_REQUESTED** [review]
domain is inactive. needs updated, or PR closed

**Comment by SgtPooki** [comment]
it looks like shake.speare is still failing all checks at the preview URL: 

image

**Pull request closed without merging**
